project:
  type: website
  output-dir: ../_site/en   
  render:
    - "*.qmd"              
    
    
website:
  title: "Gustavo Roa"
  navbar:
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
      - href: about/
        text: About
      - href: research/
        text: Research & Teaching
      - href: publications/
        text: Publications & Talks
      - href: resources/
        text: Digital Resources
      - href: cv/
        text: CV
    right:
      - text: ğŸŒ EspaÃ±ol
        href: ../es/
      - text: ğŸŒ English
        href: ../en/

lang: en

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
