project:
  type: website
  output-dir: ../_site/es   
  render:
    - "*.qmd"               

website:
  title: "Gustavo Roa"
  navbar:
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Inicio
      - href: sobre.qmd
        text: Sobre mÃ­
      - href: investigacion.qmd
        text: InvestigaciÃ³n y EnseÃ±anza
      - href: publicaciones.qmd
        text: Publicaciones y Ponencias
      - href: recursos.qmd
        text: Recursos Digitales
      - href: cv.qmd
        text: CV
    right:
      - text: ğŸŒ EspaÃ±ol
        href: ../es/
      - text: ğŸŒ English
        href: ../en/

lang: es

format:
  html:
    theme:
      - yeti
    css: ../styles.css
    toc: true
